//
// XYPlotDefaults.H -- Default values for XY Plotter
//

#ifndef _XYPLOTDEFAULTS_H
#define _XYPLOTDEFAULTS_H

#define DEF_MARK_FLAG		"off"
#define DEF_LARGEMARK_FLAG	"off"
#define DEF_STYLEMARK_FLAG      "off"
#define DEF_TICK_FLAG		"off"
#define DEF_TICKAXIS_FLAG	"off"
#define DEF_BB_FLAG		"off"
#define DEF_PLOTLINE_FLAG	"on"
#define DEF_DISPHINTS_FLAG      "on"

#define DEF_LINE_WIDTH		"0"
#define DEF_GRID_WIDTH		"0"
#define DEF_DOT_WIDTH           "8"

#define DEF_XUNIT_TEXT_X     "X"
#define DEF_XUNIT_TEXT_Y     "Y"
#define DEF_XUNIT_TEXT_Z     "Z"

#define DEF_YUNIT_TEXT		"Val"
#define DEF_FMT_X		"%.2f"
#define DEF_FMT_Y		"%.2f"

#define DEF_GRID_STYLE		"10"
#define DEF_LABEL_FONT		"fixed"
#define DEF_TITLE_FONT		"fixed"

#define DEF_INIT_WIN_WIDTH      "250"
#define DEF_INIT_WIN_HEIGHT     "275"
#define DEF_INIT_WIN_OFFSET_X   "0"
#define DEF_INIT_WIN_OFFSET_Y   "450"

// Black and white defaults
#define DEF_BW_BACKGROUND	"white"
#define DEF_BW_BORDER		"black"
#define DEF_BW_FOREGROUND	"black"

// Color defaults
#define DEF_COL_BACKGROUND	"#ccc"
#define DEF_COL_BORDER		"black"
#define DEF_COL_FOREGROUND	"black"
#define DEF_COL_FIRSTSTYLE	"1"
#define DEF_GRID_COLOR          "gray"
#define DEF_TEXT_COLOR          "white"

#define DEF_INT		"0"
#define DEF_STR		""
#define DEF_FONT	"fixed"
#define DEF_PIXEL	"black"
#define DEF_STYLE	"1"
#define DEF_BOOL	"false"
#define DEF_DBL		"0.0"

#define DEF_MAX_FONT	1024
#define DEF_MAX_NAMES	10

#endif
